In [471]:
# # Parte 1. Conceptos
# # 1. Que es aprendizaje supervisado?
# Es un aprendizaje donde el modelo que va a aprender tiene los datos con sus respuestas conocidas de principio comparando con sus datos los valores
# # 2. Que es una variable objetivo?
# La variable objetivo es la cual va a compararse el resultado
# # 3. Que significa `venta_alta`?
# Una columna que nos clasifica el total de la venta, pero no numericamente
# # 4. Que diferencia hay entre `X` e `y`?
# Que X se utiliza como variables de entrada las cuales son las columnas del modelo con las que ira aprendiendo e y es la variable que tendrá para 
# predecir los datos
# # 5. Que es clasificacion?
# Es un aprendisaje que nos ayuda a juntar por así decir ciertos criterios que tenemos para las cosas
# # 6. Por que este problema es de clasificacion?
# Porque se usa el valor de la columna como clasificación, es decir, no requiere que sepamos el valor de la venta como tal (1500, 125, 345) si no más bien
# la o las reglas que sirven para clasificar según sea el caso calculado con el total de la venta (0, 1)
# # 7. Que hace `DecisionTreeClassifier`?
# Va tomando desiciones conforme avanzamos, es decir que toma desiciones de forma sistematica, y dependiendo de como vaya con sus casos, va llendose
# a las distintas ramas hasta llegar al final
# # 8. Para que sirve separar entrenamiento y prueba?
# Para separar los datos con los que el modelo aprendera y los datos con los que la prueba, separando la muestra de los datos
# # 9. Que significa exactitud?
# Significa saber que porcentaje del total de los datos fue correcto e incorrecto, entonces si tiene un 0.6 es un 60% de exactitud
# # 10. Para que sirve una matriz de confusion?
# Para saber con exactitud los resultados que salieron de los datos que se probaron, los verdaderos positivos, los verdaderos negativos,
# los falsos positivos y los falsos negativos
# # 11. Que significa `fit()`?
# Significa adaptar los datos para entrenar al modelo
# # 12. Que significa `predict()`?
# Significa predecir con los datos que le pasamos para que haga su predicción
# # 13. Por que se usa `pd.get_dummies()`?
# Para pasar las columnas que son textos a binarios, ya que el get_dummies lo que hace es una columna por valor unico
# # 14. Por que se usa `reindex()` al predecir ventas nuevas?
# Para forzar a despues de hacer el get_dummies que las columnas sean las mismas que se usaron al entrenar, entonces si una nueva columna cuando se hace
# el get_dummies aparece con el reindex se ignora
# # 15. Por que una prediccion no es una verdad absoluta?
# Porque depende de los datos que haya y puede haber casos donde sea erroneo y se marque como correcto, por eso debemos de tomarlo como una forma de 
# datos que nos ayuda a ver la manera y evolución de los mismos, sin confiar totalmente en ellos

In [472]:
## Parte 2. Revision Del Dataset

In [473]:
# 1. Muestra las primeras filas.
import pandas as pd
df = pd.read_csv("ventas_ecommerce_limpio.csv")
df.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta
0,1001,2026-07-01,Ana Lopez,Mouse,Accesorios,1,250.0,Efectivo,Cuernavaca,250.0
1,1002,2026-07-01,Luis Perez,Teclado,Accesorios,1,650.0,Tarjeta,Jiutepec,650.0
2,1003,2026-07-02,Sofia Ruiz,Audifonos,Accesorios,1,900.0,Tarjeta,Temixco,900.0
3,1004,2026-07-02,Pedro Mata,Webcam,Accesorios,1,800.0,Efectivo,Cuernavaca,800.0
4,1005,2026-07-03,Laura Diaz,Cable HDMI,Accesorios,2,180.0,Efectivo,Jiutepec,360.0

In [474]:
# 2. Revisa las columnas.
df.columns

Index(['id_venta', 'fecha', 'cliente', 'producto', 'categoria', 'cantidad',
       'precio_unitario', 'metodo_pago', 'ciudad', 'total_venta'],
      dtype='object')

In [475]:
# 3. Muestra cuantas filas y columnas tiene.
df.shape

(60, 10)

In [476]:
# 4. Revisa si hay valores nulos.
df.isnull().sum()

id_venta           0
fecha              0
cliente            0
producto           0
categoria          0
cantidad           0
precio_unitario    0
metodo_pago        0
ciudad             0
total_venta        0
dtype: int64

In [477]:
# 5. Verifica que exista la columna `total_venta`.
df.head()
# si existe

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta
0,1001,2026-07-01,Ana Lopez,Mouse,Accesorios,1,250.0,Efectivo,Cuernavaca,250.0
1,1002,2026-07-01,Luis Perez,Teclado,Accesorios,1,650.0,Tarjeta,Jiutepec,650.0
2,1003,2026-07-02,Sofia Ruiz,Audifonos,Accesorios,1,900.0,Tarjeta,Temixco,900.0
3,1004,2026-07-02,Pedro Mata,Webcam,Accesorios,1,800.0,Efectivo,Cuernavaca,800.0
4,1005,2026-07-03,Laura Diaz,Cable HDMI,Accesorios,2,180.0,Efectivo,Jiutepec,360.0

In [478]:
# 6. Verifica que `total_venta` coincida con `cantidad * precio_unitario`.
venta_total = df["cantidad"] * df["precio_unitario"]
df["coincide"] = venta_total == df["total_venta"]
df.head()
df["coincide"].value_counts()

coincide
True    60
Name: count, dtype: int64

In [479]:
# 7. Escribe una observacion breve sobre el estado del dataset.
# En primera instancia puedo observar que el dataset es un dataset sin valores nulos y con los datos correctamente alineados para el total de la venta
# que se obtiene con la cantidad de productos y precio unitario, también puedo ver que es una cantidad considerable de registros, no son muchos pero
# tampoco son pocos

In [480]:
## Parte 3. Variable Objetivo

In [481]:
df["venta_alta"] = df["total_venta"].apply(lambda x: 1 if x >= 1000 else 0)
df.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta,coincide,venta_alta
0,1001,2026-07-01,Ana Lopez,Mouse,Accesorios,1,250.0,Efectivo,Cuernavaca,250.0,True,0
1,1002,2026-07-01,Luis Perez,Teclado,Accesorios,1,650.0,Tarjeta,Jiutepec,650.0,True,0
2,1003,2026-07-02,Sofia Ruiz,Audifonos,Accesorios,1,900.0,Tarjeta,Temixco,900.0,True,0
3,1004,2026-07-02,Pedro Mata,Webcam,Accesorios,1,800.0,Efectivo,Cuernavaca,800.0,True,0
4,1005,2026-07-03,Laura Diaz,Cable HDMI,Accesorios,2,180.0,Efectivo,Jiutepec,360.0,True,0

In [482]:
df["venta_alta"].value_counts()

venta_alta
1    40
0    20
Name: count, dtype: int64

In [483]:
# Por que venta_alta es la variable objetivo?
# Porque es la variable la cual es la respuesta de la regla que se puso para clasificar si es venta alta o si es venta no alta, sabiendo que es la
# respuesta es considerable ponerla como variable objetivo para que los datos del entrenamiento se comparen con esta misma

In [484]:
## Parte 4. Variables De Entrada

In [485]:
X = df[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]
X.head()

   cantidad  precio_unitario   categoria metodo_pago      ciudad
0         1            250.0  Accesorios    Efectivo  Cuernavaca
1         1            650.0  Accesorios     Tarjeta    Jiutepec
2         1            900.0  Accesorios     Tarjeta     Temixco
3         1            800.0  Accesorios    Efectivo  Cuernavaca
4         2            180.0  Accesorios    Efectivo    Jiutepec

In [486]:
y = df["venta_alta"]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: venta_alta, dtype: int64

In [487]:
x = pd.get_dummies(X)
x.head()

,cantidad,precio_unitario,categoria_Accesorios,categoria_Electronica,categoria_Muebles,metodo_pago_Efectivo,metodo_pago_Tarjeta,metodo_pago_Transferencia,ciudad_Cuernavaca,ciudad_Emiliano Zapata,ciudad_Jiutepec,ciudad_Temixco
0,1,250.0,True,False,False,True,False,False,True,False,False,False
1,1,650.0,True,False,False,False,True,False,False,False,True,False
2,1,900.0,True,False,False,False,True,False,False,False,False,True
3,1,800.0,True,False,False,True,False,False,True,False,False,False
4,2,180.0,True,False,False,True,False,False,False,False,True,False

In [488]:
columnas_generadas = x.columns.to_list()
columnas_generadas

['cantidad',
 'precio_unitario',
 'categoria_Accesorios',
 'categoria_Electronica',
 'categoria_Muebles',
 'metodo_pago_Efectivo',
 'metodo_pago_Tarjeta',
 'metodo_pago_Transferencia',
 'ciudad_Cuernavaca',
 'ciudad_Emiliano Zapata',
 'ciudad_Jiutepec',
 'ciudad_Temixco']

In [489]:
# Por que no se debe usar total_venta como variable de entrada si venta_alta se creo a partir de total_venta?
# Porque es la respuesta a partir del total, lo que vendría siendo que le damos los datos con la respuesta y su equivalencia si es venta alta o es 
# venta baja

In [490]:
## Parte 5. Entrenamiento Y Evaluacion

In [491]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [492]:
# 1. Divide los datos en entrenamiento y prueba.
# 2. Usa 80% entrenamiento y 20% prueba.
# 3. Usa `random_state=42`.

X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [493]:
# 4. Entrena el modelo.
# 5. Genera predicciones con los datos de prueba.

modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [494]:
# 6. Calcula exactitud.
# 7. Muestra matriz de confusion.

y_pred = modelo.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix

exactitud = accuracy_score(y_test, y_pred)
matriz = confusion_matrix(y_test, y_pred)

print(exactitud)
print(matriz)

1.0
[[4 0]
 [0 8]]

In [495]:
# 8. Crea una tabla llamada `resultados_prueba` con:

resultados_prueba = pd.DataFrame({
    "valor_real": y_test,
    "prediccion": y_pred
})

resultados_prueba["coincide"] = resultados_prueba["valor_real"] == resultados_prueba["prediccion"]

resultados_prueba

    valor_real  prediccion  coincide
0            0           0      True
5            0           0      True
36           1           1      True
45           1           1      True
13           0           0      True
54           1           1      True
33           1           1      True
48           1           1      True
12           0           0      True
57           1           1      True
46           1           1      True
50           1           1      True

In [496]:
resultados_prueba.value_counts()

valor_real  prediccion  coincide
1           1           True        8
0           0           True        4
Name: count, dtype: int64

In [497]:
# 9. Cuenta cuantos aciertos y cuantos errores hubo.

aciertos = resultados_prueba[resultados_prueba["coincide"] == True ]
errores = resultados_prueba[resultados_prueba["coincide"] == False ]

In [498]:
len(aciertos)

12

In [499]:
len(errores)

0

In [500]:
# # 1. Cual fue la exactitud?
# La exactitud fue de 1, quiere decir que la exactitud fue del 100%
# # 2. Cuantos aciertos tuvo el modelo?
# El modelo tuvo 12 aciertos
# # 3. Cuantos errores tuvo el modelo?
# El modelo tuvo 0 errores
# # 4. Que indica la matriz de confusion?
# Indica los verdaderos positivos, verdaderos negativos, los falsos positivos y falsos negativos
# # 5. Una buena exactitud significa que el modelo ya es perfecto? Explica.
# No, porque en este caso el dataset no tuvo casos donde hubiera más variedad con lo que esta en el csv, por ende si se usa en un futuro con muchos más
# datos puede que ahí ya presente las discrepancias

In [501]:
## Parte 6. Guardar Modelo Y Columnas

In [502]:
import joblib
import os

In [503]:
joblib.dump(modelo, "modelo_examen_venta_alta.pkl")

['modelo_examen_venta_alta.pkl']

In [504]:
joblib.dump(modelo, "columnas_examen_modelo.pkl")

['columnas_examen_modelo.pkl']

In [505]:
print("modelo", os.path.exists("modelo_examen_venta_alta.pkl"))

modelo True

In [506]:
print("columnas", os.path.exists("columnas_examen_modelo.pkl"))

columnas True

In [507]:
# 1. Para que sirve guardar el modelo?
# Para ya no entrenar otro modelo cuando se necesite, en este caso lo guardariamos para ser reutilizado
# 2. Para que sirve guardar las columnas del entrenamiento?
# Para saber con exactitud las columnas con las cual el modelo fue entrenado, para poner esas y no más ni menos
# 3. Que problema puede aparecer si no guardas las columnas?
# Que cuando le pase las variables de entrada no sepa cuales columnas requiere el modelo para ser entrenado, entonces al guardarlas se con exactitud
# que columnas requiere el modelo

In [508]:
## Parte 7. Ventas Nuevas

In [509]:
examen_ventas_nuevas = pd.DataFrame([
    {
        "id_venta": 1061, "fecha": "2026-07-01", "cliente": "Ana Lopez", "producto": "Mouse", "categoria": "Electronica", "cantidad": 1, "precio_unitario": 1204, "metodo_pago": "Tarjeta", "ciudad": "Jiutepec"
    },
    {
        "id_venta": 1062, "fecha": "2026-07-01", "cliente": "Diana Flores", "producto": "PC Escritorio", "categoria": "Electronica", "cantidad": 3, "precio_unitario": 548, "metodo_pago": "Tarjeta", "ciudad": "Emiliano Zapata"
    },
    {
        "id_venta": 1063, "fecha": "2026-07-01", "cliente": "Alberto Reyes", "producto": "Disco SSD", "categoria": "Electronica", "cantidad": 2, "precio_unitario": 1244, "metodo_pago": "Tarjeta", "ciudad": "Emiliano Zapata"
    },
    {
        "id_venta": 1064, "fecha": "2026-07-01", "cliente": "Gabriel Nieto", "producto": "Silla Gamer", "categoria": "Electronica", "cantidad": 2, "precio_unitario": 1254, "metodo_pago": "Tarjeta", "ciudad": "Jiutepec"
    },
    {
        "id_venta": 1065, "fecha": "2026-07-01", "cliente": "Arturo Molina", "producto": "Laptop Gamer", "categoria": "Electronica", "cantidad": 1, "precio_unitario": 1457, "metodo_pago": "Tarjeta", "ciudad": "Emiliano Zapata"
    },
    {
        "id_venta": 1066, "fecha": "2026-07-01", "cliente": "Ivan Mejia", "producto": "Mouse", "categoria": "Accesorios", "cantidad": 2, "precio_unitario": 1379, "metodo_pago": "Tarjeta", "ciudad": "Temixco"
    },
    {
        "id_venta": 1067, "fecha": "2026-07-01", "cliente": "Alejandra Vargas", "producto": "Monitor", "categoria": "Electronica", "cantidad": 3, "precio_unitario": 1785, "metodo_pago": "Tarjeta", "ciudad": "Jiutepec"
    },
    {
        "id_venta": 1068, "fecha": "2026-07-01", "cliente": "Jorge Cano", "producto": "Tablet", "categoria": "Electronica", "cantidad": 2, "precio_unitario": 1892, "metodo_pago": "Tarjeta", "ciudad": "Emiliano Zapata"
    },
    {
        "id_venta": 1069, "fecha": "2026-07-01", "cliente": "Javier Nunez", "producto": "PC Escritorio", "categoria": "Electronica", "cantidad": 1, "precio_unitario": 1050, "metodo_pago": "Tarjeta", "ciudad": "Temixco"
    },
    {
        "id_venta": 1070, "fecha": "2026-07-01", "cliente": "Ruben Castaneda", "producto": "Laptop Gamer", "categoria": "Gamer", "cantidad": 2, "precio_unitario": 512, "metodo_pago": "Tarjeta", "ciudad": "Tezoyuca"
    }
])

examen_ventas_nuevas.to_csv("examen_ventas_nuevas.csv", index=False)

In [510]:
## Parte 8. Cargar Modelo Y Predecir

In [511]:
# 1. Carga `modelo_examen_venta_alta.pkl`.
modelo_cargado = joblib.load("modelo_examen_venta_alta.pkl")

In [512]:
# 2. Carga `columnas_examen_modelo.pkl`.
nuevas_ventas = pd.read_csv("examen_ventas_nuevas.csv")
nuevas_ventas.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad
0,1061,2026-07-01,Ana Lopez,Mouse,Electronica,1,1204,Tarjeta,Jiutepec
1,1062,2026-07-01,Diana Flores,PC Escritorio,Electronica,3,548,Tarjeta,Emiliano Zapata
2,1063,2026-07-01,Alberto Reyes,Disco SSD,Electronica,2,1244,Tarjeta,Emiliano Zapata
3,1064,2026-07-01,Gabriel Nieto,Silla Gamer,Electronica,2,1254,Tarjeta,Jiutepec
4,1065,2026-07-01,Arturo Molina,Laptop Gamer,Electronica,1,1457,Tarjeta,Emiliano Zapata

In [513]:
# 3. Carga `examen_ventas_nuevas.csv`.
print("columnas", os.path.exists("columnas_examen_modelo.pkl"))
columnas_modelo = joblib.load("columnas_examen_modelo.pkl")

columnas True

In [514]:
# 4. Selecciona las mismas variables de entrada usadas en entrenamiento.
X_nuevas = nuevas_ventas[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]

In [515]:
# 5. Aplica `pd.get_dummies()`.
x_nuevas = pd.get_dummies(X_nuevas)

In [516]:
# 6. Alinea columnas con `reindex()`.
x_nuevas = x_nuevas.reindex(columns=columnas_generadas, fill_value=0)

In [517]:
nuevas_ventas.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad
0,1061,2026-07-01,Ana Lopez,Mouse,Electronica,1,1204,Tarjeta,Jiutepec
1,1062,2026-07-01,Diana Flores,PC Escritorio,Electronica,3,548,Tarjeta,Emiliano Zapata
2,1063,2026-07-01,Alberto Reyes,Disco SSD,Electronica,2,1244,Tarjeta,Emiliano Zapata
3,1064,2026-07-01,Gabriel Nieto,Silla Gamer,Electronica,2,1254,Tarjeta,Jiutepec
4,1065,2026-07-01,Arturo Molina,Laptop Gamer,Electronica,1,1457,Tarjeta,Emiliano Zapata

In [518]:
# 7. Genera predicciones.
# 8. Agrega la columna: prediccion_venta_alta
nuevas_ventas["prediccion_venta_alta"] = modelo_cargado.predict(x_nuevas)

In [519]:
# 9. Agrega la columna: interpretacion_prediccion
nuevas_ventas["interpretacion_prediccion"] = nuevas_ventas["prediccion_venta_alta"].map({
    0: "Venta no alta",
    1: "Venta alta"
})

In [520]:
# 10. Guarda el resultado como: examen_predicciones.csv
nuevas_ventas.to_csv("examen_predicciones.csv", index=False)

In [521]:
# Que podria pasar si no usas reindex antes de predecir?
# Las columnas no se alinearian con las que el modelo requiere para el entrenamiento

In [522]:
## Parte 9. Auditoria Del Modelo
# 1. Calcula: total_estimado = cantidad * precio_unitario
nuevas_ventas["total_estimado"] = nuevas["cantidad"] * nuevas["precio_unitario"]

In [523]:
# 2. Crea: venta_alta_real_estimada
nuevas_ventas["venta_alta_real_estimada"] = nuevas_ventas["total_estimado"].apply(lambda x: 1 if x >= 1000 else 0)

In [524]:
# 3. Compara: prediccion_venta_alta venta_alta_real_estimada
nuevas_ventas["coincide"] = nuevas_ventas["prediccion_venta_alta"] == nuevas_ventas["venta_alta_real_estimada"]

In [525]:
# 4. Crea la columna: coincide
nuevas_ventas["coincide"].value_counts()

coincide
True     9
False    1
Name: count, dtype: int64

In [526]:
# 5. Cuenta cuantas predicciones coincidieron y cuantas no.
# 6. Filtra las ventas que no coincidieron.
# 7. Revisa si los errores estan cerca del limite de 1000.
# 8. Guarda de nuevo `examen_predicciones.csv` con las columnas de auditoria.

errores = nuevas_ventas[nuevas_ventas["coincide"] == False]

nuevas_ventas["distancia_a_1000"] = (nuevas_ventas["total_estimado"] - 1000).abs()

cerca_limite = nuevas_ventas[nuevas_ventas["distancia_a_1000"] <= 200]

nuevas_ventas.to_csv("examen_predicciones.csv", index=False)

In [527]:
nuevas_ventas.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,prediccion_venta_alta,interpretacion_prediccion,total_estimado,venta_alta_real_estimada,coincide,distancia_a_1000
0,1061,2026-07-01,Ana Lopez,Mouse,Electronica,1,1204,Tarjeta,Jiutepec,1,Venta alta,1204,1,True,204
1,1062,2026-07-01,Diana Flores,PC Escritorio,Electronica,3,548,Tarjeta,Emiliano Zapata,1,Venta alta,1644,1,True,644
2,1063,2026-07-01,Alberto Reyes,Disco SSD,Electronica,2,1244,Tarjeta,Emiliano Zapata,1,Venta alta,2488,1,True,1488
3,1064,2026-07-01,Gabriel Nieto,Silla Gamer,Electronica,2,1254,Tarjeta,Jiutepec,1,Venta alta,2508,1,True,1508
4,1065,2026-07-01,Arturo Molina,Laptop Gamer,Electronica,1,1457,Tarjeta,Emiliano Zapata,1,Venta alta,1457,1,True,457

In [528]:
errores

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,prediccion_venta_alta,interpretacion_prediccion,total_estimado,venta_alta_real_estimada,coincide
5,1066,2026-07-01,Ivan Mejia,Mouse,Accesorios,2,1379,Tarjeta,Temixco,0,Venta no alta,2758,1,False

In [530]:
# # 1. Cuantas ventas nuevas evaluaste?
# 10 ventas nuevas
# # 2. Cuantas fueron predichas como venta alta? 9 ventas como alta
# # 3. Cuantas fueron predichas como venta no alta? 1 venta como no alta
# nuevas_ventas["prediccion_venta_alta"].value_counts()
# # 4. Cuantas coincidieron con la regla manual? 9 coincidieron
# # 5. Cuantas no coincidieron? 1 no coincidio
# # 6. Que ventas no coincidieron? la venta 1066
# # 7. Los errores estuvieron cerca del limite de 1000? noo, estuvo muy lejos
# # 8. Que paso con la categoria nueva? no se muestra
# # 9. Que paso con la ciudad nueva? no se muestra