In [1]:
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
df = pd.read_csv('ventas_ecommerce_limpio.csv')

In [3]:
# 1. Muestra las primeras filas.
df.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta
0,1001,2026-07-01,Ana Lopez,Mouse,Accesorios,1,250.0,Efectivo,Cuernavaca,250.0
1,1002,2026-07-01,Luis Perez,Teclado,Accesorios,1,650.0,Tarjeta,Jiutepec,650.0
2,1003,2026-07-02,Sofia Ruiz,Audifonos,Accesorios,1,900.0,Tarjeta,Temixco,900.0
3,1004,2026-07-02,Pedro Mata,Webcam,Accesorios,1,800.0,Efectivo,Cuernavaca,800.0
4,1005,2026-07-03,Laura Diaz,Cable HDMI,Accesorios,2,180.0,Efectivo,Jiutepec,360.0

In [4]:
# 2. Revisa las columnas.
df.columns

Index(['id_venta', 'fecha', 'cliente', 'producto', 'categoria', 'cantidad',
       'precio_unitario', 'metodo_pago', 'ciudad', 'total_venta'],
      dtype='object')

In [5]:
# 3. Muestra cuantas filas y columnas tiene.
df.shape

(60, 10)

In [14]:
# 4. Revisa si hay valores nulos.
df.isnull().sum()

id_venta           0
fecha              0
cliente            0
producto           0
categoria          0
cantidad           0
precio_unitario    0
metodo_pago        0
ciudad             0
total_venta        0
dtype: int64

In [13]:
# 5. Verifica que exista la columna `total_venta`.
df['total_venta'].head()

0    250.0
1    650.0
2    900.0
3    800.0
4    360.0
Name: total_venta, dtype: float64

In [15]:
# 6. Verifica que `total_venta` coincida con `cantidad * precio_unitario`.
df["total_calculado"] = df["cantidad"] * df["precio_unitario"]

In [16]:
# Revisar coincidencias
df[df["total_venta"] != df["total_calculado"]]

Empty DataFrame
Columns: [id_venta, fecha, cliente, producto, categoria, cantidad, precio_unitario, metodo_pago, ciudad, total_venta, total_calculado]
Index: []

In [17]:
# 7. Escribe una observacion breve sobre el estado del dataset.
# El dataset no cuenta con valores nulos y no se encontraron inconsistencias en 'total_venta'

In [18]:
# PARTE 3

In [20]:
# Crear la columna venta_alta
df['venta_alta'] = df['total_venta'].apply(lambda x:1 if x>= 1000 else 0)
df.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,total_venta,total_calculado,venta_alta
0,1001,2026-07-01,Ana Lopez,Mouse,Accesorios,1,250.0,Efectivo,Cuernavaca,250.0,250.0,0
1,1002,2026-07-01,Luis Perez,Teclado,Accesorios,1,650.0,Tarjeta,Jiutepec,650.0,650.0,0
2,1003,2026-07-02,Sofia Ruiz,Audifonos,Accesorios,1,900.0,Tarjeta,Temixco,900.0,900.0,0
3,1004,2026-07-02,Pedro Mata,Webcam,Accesorios,1,800.0,Efectivo,Cuernavaca,800.0,800.0,0
4,1005,2026-07-03,Laura Diaz,Cable HDMI,Accesorios,2,180.0,Efectivo,Jiutepec,360.0,360.0,0

In [21]:
# Por que venta_alta es la variable objetivo? Porque se busca clasificar si una venta fue alta o no lo fue en base al monto de la misma

In [22]:
# PARTE 4 VARIABLES DE ENTRADA

In [24]:
# Definir variables de entrada
X = df[['cantidad', 'precio_unitario', 'categoria', 'metodo_pago', 'ciudad']]

In [25]:
# Usa como variable objetivo: venta_alta
y = df['venta_alta']

In [26]:
# 3. Convierte variables categoricas con `pd.get_dummies()`.
X = pd.get_dummies(X)

In [27]:
# 4. Guarda la lista de columnas generadas.
cols_modelo = X.columns.tolist()

In [28]:
# 5. Muestra las primeras filas de `X` despues de `get_dummies()`.
X.head()

,cantidad,precio_unitario,categoria_Accesorios,categoria_Electronica,categoria_Muebles,metodo_pago_Efectivo,metodo_pago_Tarjeta,metodo_pago_Transferencia,ciudad_Cuernavaca,ciudad_Emiliano Zapata,ciudad_Jiutepec,ciudad_Temixco
0,1,250.0,True,False,False,True,False,False,True,False,False,False
1,1,650.0,True,False,False,False,True,False,False,False,True,False
2,1,900.0,True,False,False,False,True,False,False,False,False,True
3,1,800.0,True,False,False,True,False,False,True,False,False,False
4,2,180.0,True,False,False,True,False,False,False,False,True,False

In [29]:
# Parte 5. Entrenamiento Y Evaluacion

In [31]:
# 1. Divide los datos en entrenamiento y prueba.
# 2. Usa 80% entrenamiento y 20% prueba.
# 3. Usa `random_state=42`.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [32]:
# 4. Entrena el modelo.
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [33]:
# 5. Genera predicciones con los datos de prueba.
y_pred = modelo.predict(X_test)

In [35]:
# 6. Calcula exactitud.
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud:", exactitud)

Exactitud: 1.0

In [36]:
# 7. Muestra matriz de confusion.
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[4 0]
 [0 8]]

In [37]:
# 8. Crea una tabla llamada `resultados_prueba` con:
# valor_real
# prediccion
# coincide
resultados_prueba = pd.DataFrame({
    "valor_real": y_test,
    "prediccion": y_pred
})

resultados_prueba["coincide"] = resultados_prueba["valor_real"] == resultados_prueba["prediccion"]

In [38]:
# 9. Cuenta cuantos aciertos y cuantos errores hubo.
aciertos = resultados_prueba[resultados_prueba["coincide"] == True]
len(aciertos)

12

In [39]:
errores = resultados_prueba[resultados_prueba["coincide"] == False]
len(errores)

0

In [40]:
# Preguntas obligatorias:
# 1. Cual fue la exactitud? de 1.0
# 2. Cuantos aciertos tuvo el modelo? tuvo 12
# 3. Cuantos errores tuvo el modelo? no tuvo ninguno
# 4. Que indica la matriz de confusion? que clasificó 4 ventas altas correctamente y no clasificó ventas altas incorrectamente; que las 8 no altas las clasificó correctamente como no altas
# 5. Una buena exactitud significa que el modelo ya es perfecto? Explica. No, un modelo siempre se puede equivocar, solo significa que tiene mayor proporción de acertar las predicciones

In [41]:
## Parte 6. Guardar Modelo Y Columnas
# Guarda:
# modelo_examen_venta_alta.pkl
# columnas_examen_modelo.pkl

# Indicaciones:

# 1. Usa `joblib`.
# 2. Guarda el modelo entrenado.
joblib.dump(modelo, 'modelo_examen_venta_alta.pkl')

['modelo_examen_venta_alta.pkl']

In [42]:
# 3. Guarda la lista de columnas usadas durante el entrenamiento.
joblib.dump(cols_modelo, 'columnas_examen_modelo.pkl')

['columnas_examen_modelo.pkl']

In [44]:
import os

In [46]:
# 4. Verifica que los archivos aparezcan en tu carpeta.
print('Se encontró el modelo: ', os.path.exists('modelo_examen_venta_alta.pkl'))

Se encontró el modelo:  True

In [47]:
print('Se encontraron las columnas: ', os.path.exists('columnas_examen_modelo.pkl'))

Se encontraron las columnas:  True

In [48]:
# Preguntas obligatorias:
# 1. Para que sirve guardar el modelo? Para poder reutilizarlo después con otros volumenes de datos similares sin tener que entrenarlo desde cero
# 2. Para que sirve guardar las columnas del entrenamiento? para conocer las columnas o variables con las que trabaja el modelo y poder alinearlas
# 3. Que problema puede aparecer si no guardas las columnas? puede provocar errores en las predicciones al tener datos diferentes

In [50]:
# Parte 7. Ventas Nuevas
# Crea un archivo llamado:
# examen_ventas_nuevas.csv
ventas_nuevas = pd.DataFrame({
    "id_venta": [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010],
    "fecha": ["2026-08-07", "2026-08-07", "2026-06-07", "2026-06-09", "2026-08-09", "2026-06-10", "2026-08-08", "2026-07-09", "2026-07-10", "2026-08-10"],
    "cliente": ["Lizeth Torres", "Maria Torres", "Martinillo", "Alondra Medina", "Angela Castro", "Ana Karen", "Rosa Rodriguez", "Luis Peñaloza", "Esmeralda Colocia", "Hector Morales"],
    "producto": ["Mouse", "Laptop", "Sala", "Mouse", "PC Gamer", "Playera", "Tenis", "Blusa", "Comedor", "Sillon"],
    "categoria": ["Accesorios", "Electronica", "Muebles", "Accesorios","Electronica", "Ropa", "Ropa", "Ropa", "Muebles", "Muebles"],
    "cantidad": [1, 1,1,1,1, 2, 1, 3, 1, 1],
    "precio_unitario": [500, 12000, 7000, 200, 15000, 450, 1100, 350, 16700, 8000],
    "metodo_pago": ["Efectivo", "Tarjeta","Efectivo", "Tarjeta","Efectivo", "Tarjeta","Efectivo", "Tarjeta","Efectivo", "Tarjeta"],
    "ciudad": ["Cuernavaca", "Jiutepec","Cuernavaca", "Jiutepec", "Temixco", "Tepoztlan","Cuernavaca", "Jiutepec", "Emiliano Zapata", "Temixco"]
})

In [51]:
ventas_nuevas.to_csv("examen_ventas_nuevas.csv", index=False)

In [52]:
# Parte 8. Cargar Modelo Y Predecir

In [55]:
# 1. Carga `modelo_examen_venta_alta.pkl`.
modelo_cargado = joblib.load('modelo_examen_venta_alta.pkl')

In [56]:
# 2. Carga `columnas_examen_modelo.pkl`.
columnas = joblib.load('columnas_examen_modelo.pkl')

In [58]:
# 3. Carga `examen_ventas_nuevas.csv`.
nuevas = pd.read_csv("examen_ventas_nuevas.csv")

In [59]:
# 4. Selecciona las mismas variables de entrada usadas en entrenamiento.
X_nuevas = nuevas[["cantidad", "precio_unitario", "categoria", "metodo_pago", "ciudad"]]

In [60]:
# 5. Aplica `pd.get_dummies()`.
X_nuevas = pd.get_dummies(X_nuevas)

In [61]:
# 6. Alinea columnas con `reindex()`.
X_nuevas = X_nuevas.reindex(columns=columnas, fill_value=0)

In [63]:
# 7. Genera predicciones.
predicciones = modelo_cargado.predict(X_nuevas)

In [64]:
# 8. Agrega la columna: prediccion_venta_alta
nuevas["prediccion_venta_alta"] = predicciones

In [65]:
nuevas.head()

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,prediccion_venta_alta
0,2001,2026-08-07,Lizeth Torres,Mouse,Accesorios,1,500,Efectivo,Cuernavaca,0
1,2002,2026-08-07,Maria Torres,Laptop,Electronica,1,12000,Tarjeta,Jiutepec,1
2,2003,2026-06-07,Martinillo,Sala,Muebles,1,7000,Efectivo,Cuernavaca,1
3,2004,2026-06-09,Alondra Medina,Mouse,Accesorios,1,200,Tarjeta,Jiutepec,0
4,2005,2026-08-09,Angela Castro,PC Gamer,Electronica,1,15000,Efectivo,Temixco,1

In [66]:
# 9. Agrega la columna: interpretacion_prediccion
nuevas["interpretacion_prediccion"] = nuevas["prediccion_venta_alta"].map({
    0: "Venta no alta",
    1: "Venta alta"
})

In [67]:
# 10. Guarda el resultado como: examen_predicciones.csv
nuevas.to_csv('examen_predicciones.csv', index=False)

In [68]:
# Pregunta obligatoria:
# Que podria pasar si no usas reindex antes de predecir? El modelo pordía fallar y generar predicciones erroneas

In [69]:
# Parte 9. Auditoria Del Modelo
# 1. Calcula: total_estimado = cantidad * precio_unitario
nuevas["total_estimado"] = nuevas["cantidad"] * nuevas["precio_unitario"]

In [70]:
# 2. Crea: venta_alta_real_estimada usando: 
# Si total_estimado >= 1000, entonces 1
# Si total_estimado < 1000, entonces 0
nuevas["venta_alta_real_estimada"] = nuevas["total_estimado"].apply(lambda x: 1 if x >= 1000 else 0)

In [71]:
# 3. Compara:
# prediccion_venta_alta
# venta_alta_real_estimada
# 4. Crea la columna:  coincide
nuevas["coincide"] = nuevas["prediccion_venta_alta"] == nuevas["venta_alta_real_estimada"]

In [72]:
# 5. Cuenta cuantas predicciones coincidieron y cuantas no.
nuevas["coincide"].value_counts()

coincide
True     9
False    1
Name: count, dtype: int64

In [74]:
# 6. Filtra las ventas que no coincidieron.
errores = nuevas[nuevas["coincide"] == False]
errores

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,prediccion_venta_alta,interpretacion_prediccion,total_estimado,venta_alta_real_estimada,coincide
5,2006,2026-06-10,Ana Karen,Playera,Ropa,2,450,Tarjeta,Tepoztlan,1,Venta alta,900,0,False

In [75]:
# 7. Revisa si los errores estan cerca del limite de 1000.
nuevas["distancia_a_1000"] = (nuevas["total_estimado"] - 1000).abs()
cerca_limite = nuevas[nuevas["distancia_a_1000"] <= 200]
cerca_limite

,id_venta,fecha,cliente,producto,categoria,cantidad,precio_unitario,metodo_pago,ciudad,prediccion_venta_alta,interpretacion_prediccion,total_estimado,venta_alta_real_estimada,coincide,distancia_a_1000
5,2006,2026-06-10,Ana Karen,Playera,Ropa,2,450,Tarjeta,Tepoztlan,1,Venta alta,900,0,False,100
6,2007,2026-08-08,Rosa Rodriguez,Tenis,Ropa,1,1100,Efectivo,Cuernavaca,1,Venta alta,1100,1,True,100
7,2008,2026-07-09,Luis Peñaloza,Blusa,Ropa,3,350,Tarjeta,Jiutepec,1,Venta alta,1050,1,True,50

In [76]:
# 8. Guarda de nuevo `examen_predicciones.csv` con las columnas de auditoria.
nuevas.to_csv("examen_predicciones.csv", index=False)

In [77]:
 nuevas["prediccion_venta_alta"].value_counts()

prediccion_venta_alta
1    8
0    2
Name: count, dtype: int64

In [78]:
# Preguntas obligatorias:
# 1. Cuantas ventas nuevas evaluaste? 10 nuevas
# 2. Cuantas fueron predichas como venta alta? 8 ventas
# 3. Cuantas fueron predichas como venta no alta? 2 ventas
# 4. Cuantas coincidieron con la regla manual? Coincidieron 9
# 5. Cuantas no coincidieron? 1 no coincidió
# 6. Que ventas no coincidieron? la venta 2006
# 7. Los errores estuvieron cerca del limite de 1000? Si, fue de 900 el total
# 8. Que paso con la categoria nueva? Se alineó e las columnas del modelo, pero este falló en una venta con esta categoría nueva
# 9. Que paso con la ciudad nueva? se agregó un nueva ciudad y el modelo falló justo en esa prediccion, sin embargo se alineó correctamente a las columnas